abbreviations = {
    'ASAP':'As soon as possible	',
    'FAQs':'Frequently asked questions',
    'ID':'Identification',
    'ATM':'Automatic teller machine',
    'VIP':'Very important person',
    'POV':'Point of view',
    'TMI':'Too much information',
    'PIN':'Personal identification number',
    'i.g.':'For example',
    'i.e.':'In other words',
    'univ.': 'university',
    'gov.': 'government',
    'Auth':'author',
    'Arith':'arithmetic',
    'Arab':'Arabic',
    'Apr':'April',
    'Applic':'application',
    'Mr.': 'Mister',
    'Mrs.': 'Misses',
    'Ms.': 'Miss',
    'Dr.': 'Doctor',
    'Co.': 'Company',
    'Ltd.': 'Limited',
    'St.': 'Saint',
    'Rd.': 'Road',
    'Ave.': 'Avenue',
    'apt.': 'apartment',
    'bldg.': 'building',
    'dept.': 'department',
    'ISBN': 'International Standard Book Number',
    'USA': 'United States of America',
    'US': 'United States',
    'UK': 'United Kingdom',
    'GF': 'Girlfriend',
    'GW': 'George W. Bus',
    'Feb.': 'february',
    'NY': 'New York',
    'CA': 'California',
    'TX': 'Texas',
    'est.': 'established',
    'inc.': 'incorporated',
    'a.m.': 'ante meridiem',
    'p.m.': 'post meridiem',
    'AM': 'ante meridiem',
    'PM': 'post meridiem',
    'etc.': 'et cetera',
    'e.g.': 'exempli gratia',
    'LA': 'Los Angeles',
    'Mgr.': 'Manager',
    'CFO': 'Chief Financial Officer',
    'CEO': 'Chief Executive Officer',
    'VP': 'Vice President',
    'ASAP': 'As Soon As Possible',
    'FAQ': 'Frequently Asked Questions',
    'FYI': 'For Your Information',
    'DIY': 'Do It Yourself',
    'ETA': 'Estimated Time of Arrival',
    'TGIF': 'Thank God It\'s Friday',
    'LOL': 'Laughing Out Loud',
    'BRB': 'Be Right Back',
    'OMG': 'Oh My God',
    'BTW': 'By The Way',
    'TTYL': 'Talk To You Later',
    'WIP': 'Work In Progress',
    'POV': 'Point Of View',
    'IMO': 'In My Opinion',
    'FWIW': 'For What It\'s Worth',
    'TBA': 'To Be Announced',
    'TBD': 'To Be Determined',
    'AC' : 'Alternating Current ',
    'bar-b-que' : 'barbecue' ,
    'AFAIK': 'As Far As I Know',
    'AKA': 'Also Known As',
    'BFF': 'Best Friends Forever',
    'BTW': 'By The Way',
    'CUL8R': 'See You Later',
    'FYI': 'For Your Information',
    'IDK': 'I Don\'t Know',
    'IMO': 'In My Opinion',
    'IRL': 'In Real Life',
    'JK': 'Just Kidding',
    'LOL': 'Laugh Out Loud',
    'N/A': 'Not Applicable',
    'OMG': 'Oh My God',
    'ROFL': 'Rolling On the Floor Laughing',
    'TMI': 'Too Much Information',
    'TTYL': 'Talk To You Later',
    'WTF': 'What The F***',
    'YOLO': 'You Only Live Once',
    'BRB': 'Be Right Back',
    'G2G': 'Got To Go',
    'IDC': 'I Do not Care',
    'LMAO': 'Laughing My A** Off',
    'TBH': 'To Be Honest',
    'WTH': 'What The Heck',
    'AFK': 'Away From Keyboard',
    'NSFW': 'Not Safe For Work',
    'ICYMI': 'In Case You Missed It',
    'OOTD': 'Outfit Of The Day',
    'FOMO': 'Fear Of Missing Out',
    'A/C': 'Air Conditioning',
    'CEO': 'Chief Executive Officer',
    'DIY': 'Do It Yourself',
    'ETA': 'Estimated Time of Arrival',
    'FAQ': 'Frequently Asked Questions',
    'GPS': 'Global Positioning System',
    'HR': 'Human Resources',
    'IQ': 'Intelligence Quotient',
    'JPEG': 'Joint Photographic Experts Group',
    'KPI': 'Key Performance Indicator',
    'LCD': 'Liquid Crystal Display',
    'MRI': 'Magnetic Resonance Imaging',
    'NASA': 'National Aeronautics and Space Administration',
    'PDF': 'Portable Document Format',
    'Q&A': 'Questions and Answers',
    'R&D': 'Research and Development',
    'SMS': 'Short Message Service',
    'TBA': 'To Be Announced',
    'USB': 'Universal Serial Bus',
    'VPN': 'Virtual Private Network',
    'WiFi': 'Wireless Fidelity',
    'XOXO': 'Hugs and Kisses',
    'YTD': 'Year to Date',
    'ZIP': 'Zone Improvement Plan',
    'AM': 'Ante Meridiem',
    'PM': 'Post Meridiem',
    'B2B': 'Business-to-Business',
    'BFF': 'Best Friends Forever',
    'BTW': 'By the Way',
    'CC': 'Carbon Copy',
    'DM': 'Direct Message',
    'FYI': 'For Your Information',
    'GMT': 'Greenwich Mean Time',
    'HTML': 'Hypertext Markup Language',
    'IDK': 'I Do not Know',
    'LOL': 'Laugh Out Loud',
    'MBA': 'Master of Business Administration',
    'N/A': 'Not Applicable',
    'OMG': 'Oh My God',
    'POV': 'Point of View',
    'ROFL': 'Rolling On the Floor Laughing',
    'SOS': 'Save Our Souls',
    'TBH': 'To Be Honest',
    'TGIF': 'Thank God It is Friday',
    'TTYL': 'Talk to You Later',
    'WTF': 'What the F***',
    'YOLO': 'You Only Live Once',
    'WWII': 'World War II',
    'bro' : 'brother'
}