# Abbreviations_Quora.py

abbreviations = {
    "i'm": "i am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "can't": "cannot",
    "won't": "will not",
    "don't": "do not",
    "doesn't": "does not",
    "didn't": "did not",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "wouldn't": "would not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "mustn't": "must not",
    "mightn't": "might not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "there's": "there is",
    "here's": "here is",
    "what's": "what is",
    "who's": "who is",
    "where's": "where is",
    "how's": "how is",
    "let's": "let us",
    "i've": "i have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "i would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "i will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "ain't": "is not",
    "u": "you",
    "r": "are",
    "ur": "your",
    "thx": "thanks",
    "pls": "please",
    "btw": "by the way",
    "lol": "laughing out loud",
    "omg": "oh my god",
    "idk": "i do not know",
    "imo": "in my opinion",
    "fyi": "for your information",
    "brb": "be right back",
    "b4": "before",
    "gr8": "great",
}
